### ISSUE TITLE
Problem Cannot Handled....

### ISSUE THREAD

**Issue by bhavya104** [HouariZegai/FXFaceDetection#1]
<h1> Please Help me to Solve this Issue </h1>

<h3> Hi i am bhavya sharma currently pursuing bachelor degree in computer science engineering from india. i face problem while running your application.. Please help me to solve that error.</h3>

![3ba3405d-bf55-47cf-b9d1-269bfd57c18b](https://user-images.githubusercontent.com/54014998/82865820-4b1d6980-9f45-11ea-856a-e9b35def9002.jpg)
![864b2414-251c-4ccf-9ead-fdb01650b631](https://user-images.githubusercontent.com/54014998/82865835-54a6d180-9f45-11ea-8a22-89b6d02a6c7a.jpg)

<h2> i use this open cv depedency..</h2>

![3086f4a8-dc13-4120-b33e-ed4a07afe1e2](https://user-images.githubusercontent.com/54014998/82865842-5b354900-9f45-11ea-8602-224aead8019e.jpg)

**Comment by HouariZegai** [comment]
Hello,
Maybe you have a problem with packages, try to fix it by changing it.

**Comment by bhavya104** [comment]
Done Thanks brother for helping....
